USE [master]
GO
/****** Object:  Database [DavidChat]    Script Date: 5/12/2018 12:31:50 PM ******/
CREATE DATABASE [DavidChat]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DavidChat', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\DavidChat.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'DavidChat_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\DavidChat_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [DavidChat] SET COMPATIBILITY_LEVEL = 110
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DavidChat].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [DavidChat] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [DavidChat] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [DavidChat] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [DavidChat] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [DavidChat] SET ARITHABORT OFF 
GO
ALTER DATABASE [DavidChat] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [DavidChat] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [DavidChat] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [DavidChat] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [DavidChat] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [DavidChat] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [DavidChat] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [DavidChat] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [DavidChat] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [DavidChat] SET  DISABLE_BROKER 
GO
ALTER DATABASE [DavidChat] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [DavidChat] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [DavidChat] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [DavidChat] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [DavidChat] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [DavidChat] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [DavidChat] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [DavidChat] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [DavidChat] SET  MULTI_USER 
GO
ALTER DATABASE [DavidChat] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [DavidChat] SET DB_CHAINING OFF 
GO
ALTER DATABASE [DavidChat] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [DavidChat] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [DavidChat] SET  READ_WRITE 
GO
